# Generated by Django 5.2.8 on 2026-10-08 09:16

import django.db.models.deletion
from django.db import migrations, models


def copy_primary_categories(apps, schema_editor):
    """Добавить прежнюю основную категорию в список без изменения URL и FK."""
    Product = apps.get_model("products", "Product")
    Through = Product.categories.through
    using = schema_editor.connection.alias
    batch = []
    for product_id, category_id in Product.objects.using(using).exclude(category_id=None).values_list("pk", "category_id").iterator(chunk_size=1000):
        batch.append(Through(product_id=product_id, category_id=category_id))
        if len(batch) == 1000:
            Through.objects.using(using).bulk_create(batch)
            batch = []
    if batch:
        Through.objects.using(using).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Объект отображается во всех выбранных категориях. Основная категория включается автоматически.', related_name='category_objects', to='products.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Основная категория объекта для переноса прежнего адреса. Это не родитель категории в дереве.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='products.category', verbose_name='Родительская категория (основная)'),
        ),
        migrations.RunPython(copy_primary_categories, migrations.RunPython.noop),
    ]
