# Generated by Django 5.2.8 on 2026-10-08 10:52

import apps.products.map_data
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_categories_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='map_center',
            field=models.CharField(blank=True, help_text='Долгота, широта. Если не указан, карта центрируется на метке.', max_length=255, validators=[apps.products.map_data.validate_coordinates], verbose_name='Центр карты'),
        ),
        migrations.AddField(
            model_name='product',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='Долгота, широта. Дробная часть через точку. Исходная точность сохраняется.', max_length=255, validators=[apps.products.map_data.validate_coordinates], verbose_name='Координаты метки'),
        ),
        migrations.AddField(
            model_name='product',
            name='map_source',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Исходные данные карты JBZoo'),
        ),
        migrations.AddField(
            model_name='product',
            name='map_zoom',
            field=models.PositiveSmallIntegerField(blank=True, default=12, help_text='От 0 до 19. Если не указан, используется 12.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(19)], verbose_name='Масштаб карты'),
        ),
    ]
