# Generated by Django 5.2.8 on 2026-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_map_center_product_map_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='joomla_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='ID Joomla'),
        ),
        migrations.AddField(
            model_name='product',
            name='joomla_source',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Исходные данные JBZoo'),
        ),
        migrations.AddField(
            model_name='product',
            name='joomla_url',
            field=models.CharField(blank=True, editable=False, max_length=1000, verbose_name='Исходный URL Joomla'),
        ),
    ]
