"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# -----------------------------------------------------------------------------
# Пути
# -----------------------------------------------------------------------------

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = []


# -----------------------------------------------------------------------------
# Приложения
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Сторонние
    'smart_selects',
    'easy_thumbnails',

    # Приложения проекта
    'apps.home',
    'apps.products',
    'apps.wishlist',
    'apps.reviews',
    'apps.appointments',
    'apps.size_helper',
    'apps.users',
    'apps.search',
    'apps.recommendations',
    'apps.calculator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------------------------------------------------------
# URL-конфигурация и WSGI
# -----------------------------------------------------------------------------

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# -----------------------------------------------------------------------------
# Шаблоны
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / 'config' / 'templates',
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.wishlist.context_processors.wishlist_count",
                "apps.products.context_processors.comparison_ids",
                "apps.products.context_processors.recently_viewed_ids",
                'config.context_processors.theme_context',
                'apps.recommendations.context_processors.promoted_products',

            ],
        },
    },
]




# -----------------------------------------------------------------------------
# База данных
# -----------------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# -----------------------------------------------------------------------------
# Валидация паролей
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -----------------------------------------------------------------------------
# Интернационализация
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# Статика и медиа
# -----------------------------------------------------------------------------

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"


# -----------------------------------------------------------------------------
# Хранилища
# -----------------------------------------------------------------------------

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# -----------------------------------------------------------------------------
# Email / SMTP
# Все SMTP-параметры берутся из переменных окружения.
# В dev.py backend переопределён на console.EmailBackend.
# -----------------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=465)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=True)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=False)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
MANAGER_EMAILS = [
    email.strip()
    for email in config("MANAGER_EMAILS", default="").split(",")
    if email.strip()
]

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="")
TELEGRAM_MANAGER_CHAT_ID = config("TELEGRAM_MANAGER_CHAT_ID", default="")

MAX_BOT_TOKEN = config("MAX_BOT_TOKEN", default="")
MAX_MANAGER_CHAT_ID = config("MAX_MANAGER_CHAT_ID", default="")

# -----------------------------------------------------------------------------
# Прочее
# -----------------------------------------------------------------------------

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000
SITE_ID = 1

# -----------------------------------------------------------------------------
# Логирование
# -----------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": (
                "[{asctime}] "
                "{levelname} "
                "{name}: "
                "{message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "standard",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": [
            "console",
            "file",
        ],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
                "file",
            ],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": [
                "console",
                "file",
            ],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# -----------------------------------------------------------------------------
# Авторизация
# -----------------------------------------------------------------------------

LOGIN_REDIRECT_URL = '/account/dashboard/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/'

# -----------------------------------------------------------------------------
# Тема оформления сайта
# Значения: 'default', 'wedding', 'auto', 'construction' и др.
# -----------------------------------------------------------------------------

CURRENT_THEME = 'auto'

# -----------------------------------------------------------------------------
# Этого нет!!!!!! 
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки easy-thumbnails
THUMBNAIL_ALIASES = {
    '': {
        'small': {'size': (100, 150), 'crop': True},
    },
}

# Ключ JavaScript API Яндекс Карт; без него ручные координаты остаются доступны.
YANDEX_MAPS_API_KEY = config("YANDEX_MAPS_API_KEY", default="")

# Подложка редактора координат; публичная карта использует YANDEX_MAPS_API_KEY.
MAP_EDITOR_TILE_URL = config("MAP_EDITOR_TILE_URL", default="https://tile.openstreetmap.org/{z}/{x}/{y}.png")
MAP_EDITOR_TILE_ATTRIBUTION = config("MAP_EDITOR_TILE_ATTRIBUTION", default='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors')
